name: Firebase Hosting Preview

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy Preview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase hosting:channel:deploy pr-${{ github.event.number }} --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}