name: Firebase Hosting Preview

on:
  pull_request:
    branches:
      - main

# jobs:
#   build_and_deploy:
#     name: Build and Deploy Preview
#     runs-on: ubuntu-latest

#     permissions:
#       checks: write  # Grant permission to create check runs
#       contents: read

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Install Firebase CLI
#         run: npm install -g firebase-tools

#       # Deploy to Firebase Hosting
#       - name: Deploy to Firebase
#         uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: "${{ secrets.GITHUB_TOKEN }}"
#           firebaseServiceAccount: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
#           projectId: user-inyerface-f676b
#           entryPoint: .
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: user-inyerface-f676b